spring:
  application:
    name: Mirrors
  web:
    locale: zh_CN
  profiles:
    active: dev
server:
  port: 443
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store-password: DC36AD35CD77EDAF
    key-store: classpath:application/PKCS12.license
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
---
spring:
  config:
    activate:
      on-profile: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 64MB
      file-size-threshold: 0
      max-request-size: 1024MB
      resolve-lazily: false
logging:
  file:
    name: target/log.log
  charset:
    console: UTF-8
    file: UTF-8
  level:
    com:
      example:
        mirrors: info
    org:
      springframework:
        boot: warn
        web: warn
      apache:
        tomcat: warn
        catalina: warn