spring:
  application:
    name: Mirrors
  web:
    locale: zh_CN
server:
  port: 443
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store-password: DC36AD35CD77EDAF
    key-store: classpath:application/PKCS12.license
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8