spring:
  application:
    name: Mirrors
  web:
    locale: zh_CN
  servlet:
    multipart:
      enabled: true
      max-file-size: 128MB
      file-size-threshold: 0
      max-request-size: 64MB
      resolve-lazily: false
server:
  port: 443
  ssl:
    key-alias: tomcat
    key-store-type: PKCS12
    key-store-password: DC36AD35CD77EDAF
    key-store: classpath:application/PKCS12.license
  servlet:
    encoding:
      force: true
      enabled: true
      charset: UTF-8